apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  rate_limit.conf: |
    limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;
  default.conf: |
    server {
      listen 80;
      location / {
        limit_req zone=api burst=20 nodelay;

        auth_basic "Restricted";
        auth_basic_user_file /etc/nginx/auth/.htpasswd;

        proxy_pass http://read-tracker:8080;
        proxy_buffering off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
