apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-htpasswd
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "front.labels" . | nindent 4 }}
type: Opaque
stringData:
  .htpasswd: |
    {{ .Values.secrets.htpasswd }}