apiVersion: v1
kind: Secret
metadata:
  name: nginx-htpasswd
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tracker.labels" . | nindent 4 }}
type: Opaque
stringData:
  .htpasswd: |
    {{ .Values.secrets.nginx.htpasswd }}
