apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tracker.labels" . | nindent 4 }}
data:
  rate_limit.conf: |
    limit_req_zone $binary_remote_addr zone={{ .Values.nginx.rateLimit.zone }}:10m rate={{ .Values.nginx.rateLimit.rate }};
  default.conf: |
    server {
      listen 80;

      auth_basic "Restricted";
      auth_basic_user_file /etc/nginx/auth/.htpasswd;

      location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
      }

      location /api/ {
        limit_req zone={{ .Values.nginx.rateLimit.zone }} burst={{ .Values.nginx.rateLimit.burst }} nodelay;

        proxy_pass http://read-tracker:{{ .Values.api.port }}/;
        proxy_buffering off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
