apiVersion: v1
kind: Secret
metadata:
  name: read-tracker-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tracker.labels" . | nindent 4 }}
type: Opaque
stringData:
  mongodb_uri: {{ .Values.secrets.mongodbUri | quote }}
  db_name: {{ .Values.secrets.dbName | quote }}
