apiVersion: v1
kind: Service
metadata:
  name: read-tracker
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tracker.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: read-tracker
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
