apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.api.port | quote }}