{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: {{ .Values.namespace }}
  labels:
    app: mongo
    {{- include "api.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
{{- end }}