apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
type: Opaque
stringData:
  mongodb_uri: {{ .Values.secrets.mongodbUri | quote }}
  db_name: {{ .Values.secrets.dbName | quote }}